library(ggmap)
library(wesanderson)
library(ggplot2)
library(chron)
library(plyr)
library(dplyr)
library(rgdal)
library(sp)
library(car)
library(RColorBrewer)
library(rgdal)
library(rgeos) #might need to install this one
library(scales)
library(maptools)